from __future__ import annotations
from typing import Protocol, Dict, Any


class SystemServiceProtocol(Protocol):
    def connection_ok(self) -> bool: ...
    def get_server_time(self) -> int: ...
    def get_quick_stats(self) -> Dict[str, int]: ...
    def status_overview(self) -> Dict[str, Any]: ...
    def health_check(self) -> Dict[str, Any]: ...

