# Cortex Multi-Vault AI Learning Engine Configuration

# Tag correlation settings
tag_correlation_threshold: 0.7          # Minimum correlation score to save
min_co_occurrence: 3                    # Minimum times tags must appear together
vault_scan_interval_hours: 6            # How often to scan vaults for changes

# Pattern detection settings
pattern_detection_confidence: 0.85      # Minimum confidence for pattern detection
cross_vault_analysis_enabled: true      # Enable cross-vault pattern analysis
real_time_learning: true               # Enable real-time learning from changes

# Performance settings
max_vault_size_mb: 2048                # Maximum vault size to analyze
learning_cache_ttl_hours: 24           # How long to cache learning results
parallel_processing: true              # Enable parallel vault processing
max_analysis_threads: 4                # Maximum threads for analysis

# Insight generation settings
insight_generation_enabled: true        # Generate actionable insights
min_insight_confidence: 0.6            # Minimum confidence for insights
insight_update_interval_hours: 12      # How often to update insights

# Notification settings
notifications_enabled: true            # Enable macOS notifications
notify_on_patterns: true              # Notify when new patterns detected
notify_on_correlations: true          # Notify when strong correlations found
notification_threshold: 0.85          # Minimum confidence to trigger notification

# Storage settings
data_retention_days: 365              # How long to keep learning data
log_retention_days: 30                # How long to keep log files
backup_learning_data: true            # Backup learning data daily
compression_enabled: true             # Compress stored learning data

# Advanced AI settings
semantic_analysis_enabled: false       # Enable semantic analysis (requires more resources)
natural_language_processing: false     # Enable NLP for content analysis
machine_learning_evolution: true       # Allow AI to evolve its algorithms
confidence_learning: true             # Learn from user feedback on suggestions

# Debug settings
debug_mode: false                      # Enable debug logging
verbose_logging: false                # Enable verbose logging
performance_monitoring: true          # Monitor AI performance metrics
