gap_detection:
  auto_research_enabled: true
  detection_interval_hours: 24
  enabled: true
  max_research_queries_per_gap: 5
  min_confidence_threshold: 0.6
  research_timeout_seconds: 300
quality_thresholds:
  min_authority_score: 0.6
  min_currency_score: 0.5
  min_relevance_score: 0.7
web_research:
  enabled: true
  max_concurrent_requests: 3
  max_content_length: 50000
  request_delay_seconds: 2
  user_agent: Cortex Knowledge Gap Detector/1.0
