# Cortex Learning Service Configuration

# Learning cycle frequency (in minutes)
learning_interval_minutes: 30

# Pattern detection sensitivity (0.0 - 1.0)
pattern_detection_threshold: 0.7

# Quality check frequency (in hours)
quality_check_interval_hours: 6

# Enable macOS notifications
notification_enabled: true

# Maximum age for log files (in days)
max_log_age_days: 30

# Learning rules configuration file
learning_rules_file: learning_rules.json

# Performance thresholds
performance_thresholds:
  response_time_ms: 1000
  memory_usage_mb: 500
  cpu_usage_percent: 80

# Patterns to monitor
pattern_types:
  - decision_patterns
  - project_patterns
  - ai_session_patterns
  - productivity_patterns

# Insight generation settings
insight_generation:
  min_confidence: 0.6
  min_data_points: 10
  trend_analysis_days: 30
  auto_create_files: false
  output_directory: "00-System/Services/data/insights"
  max_auto_files_per_run: 0
