from __future__ import annotations
from typing import Protocol, Dict


class SystemRepositoryProtocol(Protocol):
    def connection_ok(self) -> bool: ...
    def server_time(self) -> int: ...
    def quick_stats(self) -> Dict[str, int]: ...
    def integrity(self) -> Dict[str, int]: ...

